version: '3'
services:
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: refdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
