import Head from "next/head";
import React, { useEffect } from "react";

export default function workspace() {
  if (typeof window !== "undefined") {
    useEffect(()=>{
        window.location.href="/"
    },[])
    return (
      <>
      <Head>
        <title>Crump REF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
         {/* {user ? <MainView/> : <LoginPage />} */} 
      </>
    );
  }
}
